FROM python:3.9.2

ENV DASH_DEBUG_MODE False
ENV DASH_AUTH_MODE True

WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /app


EXPOSE 8150

CMD ["gunicorn", "-b", "0.0.0.0:8150", "--reload", "abm_refactor1:server","--timeout 600" ]
